# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' update_theta
#'
#' This is an interim function used within the winratio function that performs Gibbs sampler and returns posterior mean, covariance matrix, and event times for the proposed design, following Supplementary file S1.
#' 
#' @param N_iter Number of iterations for gibbs sampler.
#' @param dd The data at a interim analysis point for either treatment or control arm. Either use currentData.trt or currentData.ctrl.
#' @param n  Sample size at a interim analysis point for either treatment or control arm. Either use n.current.trt or n.current.ctrl.
#' @param m0  Prior mean for mu.trt/mu.ctrl.
#' @param L0  Prior covariance for mu.trt/mu.ctrl.
#' @param S0  Prior scale matrix for Sigma.trt/Sigma.ctrl.
#' @param v0  Prior degrees of freedom for Sigma.trt/Sigma.ctrl.
#' @param time_max The upper limit for the recurrence and death time sampled from truncated normal. This will set the upper limit to to time_max rather than Inf.
#' @return A list with the following components:\tabular{ll}{
#'    \code{MU} \tab A matrix with N_iter rows and two columns. Row v, v = 1, ..., N_iter, contains posterior mean vector generated from the v-th iteration of the gibbs sampler.  \cr
#'    \tab \cr
#'    \code{post_data} \tab A cube with n rows, two columns and N_iter slices. Slice v, v = 1, ..., N_iter, contains n pairs of event times sampled from bivariate lognormal distribution with mean MU and variance Sigma, where
#'                     Mu and Sigma are generated from the posterior normal and inverse-wishart distribution, respectively, from the v-th iteration of the gibbs sampler.  \cr
#'    \tab \cr
#'    \code{Sigma} \tab A cube with two rows, two columns and N_iter slices. Slice v, v = 1, ..., N_iter, contains posterior covariance matrix generated from the v-th iteration of the gibbs sampler.   \cr
#' }
update_theta <- function(N_iter, dd, n, m0, L0, S0, v0, time_max) {
    .Call(`_BayesianWinRatio_update_theta`, N_iter, dd, n, m0, L0, S0, v0, time_max)
}

#' update_theta_univariate
#'
#' This function is an interim function used within the winratio function that performs Gibbs sampler and returns posterior mean, variance, and event times (log) for the conventional designs, following Supplementary file S1.
#' 
#' @param N_iter Number of iterations for gibbs sampler.
#' @param dd The data at a interim analysis point for either treatment or control arm. Either use currentData.trt or currentData.ctrl.
#' @param n  Sample size at a interim analysis point for either treatment or control arm. Either use n.current.trt or n.current.ctrl.
#' @param m0  Prior mean for mu.trt/mu.ctrl.
#' @param L0  Prior variance for mu.trt/mu.ctrl.
#' @param v0  v0/2 is the prior shape for Sigma.trt/Sigma.ctrl.
#' @param S0  v0*S0/2 is the prior scale for Sigma.trt/Sigma.ctrl.
#' @param time_max The upper limit for the recurrence and death time sampled from truncated normal. This will set the upper limit to to time_max rather than Inf.
#' @return A list of theta. theta is A matrix with N_iter rows and two columns. Row v, v = 1, ..., N_iter, contains posterior mean vector generated from the v-th iteration of the gibbs sampler.  
update_theta_univariate <- function(N_iter, dd, n, L0, m0, v0, S0, time_max) {
    .Call(`_BayesianWinRatio_update_theta_univariate`, N_iter, dd, n, L0, m0, v0, S0, time_max)
}

#' compare
#'
#' This is an interim function used within the winratio function that calculates the IPCW-adjusted win ratio following Equations (1) - (3).
#' 
#' @param M_iter Number of iterations after burning and thinning.
#' @param n_current_ctrl  Sample size at a interim analysis point for the control arm. 
#' @param n_current_trt  Sample size at a interim analysis point for the treatment arm. 
#' @param postData  A cube with n rows, two columns and N_iter slices. Slice v, v = 1, ..., N_iter, contains n pairs of event times sampled from bivariate lognormal distribution with mean MU and variance Sigma, where
#'  Mu and Sigma are generated from the posterior normal and inverse-wishart distribution, respectively, from the v-th iteration of the gibbs sampler.
#' @param time_trt A field containing M_iter elements, each of which is a vector of length n_current_trt. These vectors store the censoring time generated from the estimated censoring distribution from the treatment arm.
#' @param time_ctrl A field containing M_iter elements, each of which is a vector of length n_current_ctrl. These vectors store the censoring time generated from the estimated censoring distribution from the control arm.
#' @param surv_trt A field containing M_iter elements, each of which is a vector of length n_current_trt. These vectors store the survival probabilities generated from the estimated censoring distribution from the treatment arm.
#' @param surv_ctrl A field containing M_iter elements, each of which is a vector of length n_current_ctrl. These vectors store the survival probabilities generated from the estimated censoring distribution from the control arm.
#' @return A list of WR. WR is a matrix with one row and M_iter columns. Each row contains the estimated win ratio for each iteration.
compare <- function(M_iter, n_current_ctrl, n_current_trt, postData, time_trt, time_ctrl, surv_trt, surv_ctrl) {
    .Call(`_BayesianWinRatio_compare`, M_iter, n_current_ctrl, n_current_trt, postData, time_trt, time_ctrl, surv_trt, surv_ctrl)
}

